# Generated by Django 3.1.1 on 2020-10-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.TextField()),
                ('check_in', models.TextField()),
                ('check_out', models.TextField()),
                ('grade', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
